<center><img src='https://raw.githubusercontent.com/Jangrae/img/master/title.png' width=500/></center>

<center><img src='https://raw.githubusercontent.com/Jangrae/img/master/practice.png' width=300/></center>

# 실습 개요

- 데이터 전처리를 할 때 자주 사용되는 처리들을 모았습니다.
- 이후 데이터 전처리를 위해서는 아래 내용 중에 막히는 부분이 있으면 안됩니다.
- 반복 학습을 위해 비슷한 처리를 여럿으로 나눴고, 한 번에 할 수 있는 처리를 여럿으로 나웠습니다.

**[처리 내용]**

- 라이브러리 불러오기(import)
- 파일 읽어오기(read_csv)
- 데이터 확인(head, tail, info, describe...)
- 중복 데이터 제거(drop_duplicates)
- 데이터 구조 변경(melt)
- 문자열 분리(split)
- 열 추가
- 데이터 형식 변경(astype)
- 가변수(Dummy Variable) 만들기(get_dummies)
- 열 이름 변경(rename)
- 데이터프레임 연결(concat)
- 불필요한 열 제거(drop)
- 데이터프레임 조인(merge)
- 결측치(NaN 값) 처리(dropna, fillna)
- 열 순서 변경
- 인덱스 초기화(reset_index)
- 롤링 & 시프트(rolling, shift)
- 반올림(round)

# 실습 목표

- 데이터 전처리를 할 때 많이 사용되는 처리 방법을 익힙니다.
- 아래 내용을 반복 학습하고 실습하여 언제든 사용할 수 있습니다.

# CP0. 데이터 전처리 기술

## 1. 라이브러리 불러오기

- 필요한 라이브러리를 불러옵니다.
- 아래 내용을 입력함에 있어 말설임이 있어서는 안됩니다.

In [0]:
# 라이브러리 불러오기

## 2. 파일 읽어오기

- 처리할 데이터를 파일에서 읽어옵니다.
- **my_sales.csv** 파일은 2015, 2016년 월별 판매 수량을 제공합니다.
- 데이터프레임 이름은 **sales**로 합니다.
- 'https://raw.githubusercontent.com/Jangrae/csv/master/my_sales.csv'

In [0]:
# 파일 불러오기

- 결과를 확인합니다.

In [0]:
# 데이터 확인

## 3. 데이터 확인


- **데이터 전처리**는 **데이터에 대한 수술**이니 **데이터를 알아야** 수술을 할 수 있습니다.

**1) 상위, 하위 n 건씩 확인**

- **head()**, **tail()** 메소드 괄호 안에 건수를 지정하지 않으면 5개 행이 조회됩니다.
- 우선 상위 행을 조회합니다.

- 이제 하위 행을 조회합니다.

**2) 열 정보와 데이터 수 확인**

- 기본적으로 **NaN** 값은 개수에 포함이 안되니, 다른 열 개수와 비교해서 NaN 값 존재 여부를 알 수 있습니다.

**3) 기초 통계 정보 확인**

- 숫자 데이터를 갖는 열들의 데이터 분포를 확인합니다.

**4) 범주형 데이터 값 확인**

- 범주형 데이터를 갖는 열이 어떤 값을 몇 개 가지고 있는지 확인합니다.
- Grade에 대한 범주형 데이터 확인

**5) 중복 데이터 확인**

- 중복된 데이터는 정확한 분석을 위해 제거해야 합니다.
- **duplicated()** 메소드로 중복된 행이 있는지 확인합니다.

- 중복된 값이 어떤 행인지 확인합니다.

## 4. 중복 데이터 제거

- 중복된 데이터는 분석에 방해가 되니 고감히 제거합니다.
- PD011 상품 정보가 완전히 중복되니 **drop_duplicates()** 메소드로 제거합니다.

## 5. 데이터 구조 변경

- 열 이름이 값인 경우 그 값을 행의 데이터로 내려야 합니다.
- 열 이름이 행 데이터로 내려진 형태를 **Unpivot**이라고도 부릅니다.
- **pd.melt()** 함수를 사용합니다.
- ProductID, Grade, Location을 기준으로 **sales_long** 데이터 프레임을 만듭니다.
- var_name = 'Date', values = 'Qty'

- 결과를 확인합니다.

## 6. 열 추가

- 기존 열에서 데이터를 추출하여 새로운 열로 추가합니다.
- **yyyy-mm-yy** 형태에서 yyyy, mm, dd를 분리해 **Year**, **Month**, **Day** 열을 만듭니다.

### [방법 1]

- 구분자을 기준으로 문자열을 나눌 때 **split()** 메소드를 사용합니다.
- 데이터프레임 열에 대해 split() 함수를 사용할 때는 **str.split()** 형태로 사용합니다.
- **expand=True**로 설정하면 데이터프레임이 되고, **expand=False**로 설정하면 시리즈가 됩니다.
- 우선 잘 나뉘어 지는지 확인 합니다.

- 잘 나뉘어짐을 확인했으니 나뉜 데이터를 **ymd** 데이터프레임으로 선언합니다.
- 데이터를 확인합니다.

- ymd 데이터프레임의 열 이름을 Year, Month, Day로 변경합니다.
- 데이터를 확인합니다.

- **ymd** 프레임의 Year, Month, Day 값을 **sales_long** 데이터프레임에 Year, Month, Day 열로 추가합니다.

- 결과를 확인해 봅니다.

### [방법 2] 참고

- **pd.to_datetime()** 함수를 사용해 Date 열을 **datetime** 형식을 변경하면 날짜 정보를 얻기가 쉽습니다.
- sales_log 데이터프레임의 Date 열에 변경한 날짜 정보를 넣습니다.

- Year, Month, Day 열로 기존 데이터프레임에 년, 월, 일 정보를 저장합니다.
- 데이터프레임 열에 대해 날짜 정보를 얻을 때는 **dt.year**, **dt.month**, **dt.day** 속성을 사용합니다.

- 결과를 확인해 봅니다.

## 7. 데이터 형식 변경

- 문자열 형태인 Year, Month, Day를 정수형 데이터로 변경합니다.
- **astype()** 메소드를 사용해 정수형으로 변경합니다.

- 결과를 확인합니다.

## 8. 가변수(Dummy Variable) 만들기

- **pd.get_dummies()** 함수를 사용해 가변수를 만들어 새로운 데이터프레임으로 선언합니다.
- Grade 열을 기준으로 데이터프레임 이름은 **grade_dummy**로 합니다.

- 결과를 확인합니다.

## 9. 열 이름 변경 #1

- 가변수 열 이름을 이해하기 쉽게고 의미있게 변경합니다.
- 컬럼 이름을 grade_a, grade_b,grade_c, grade_d로 변경합니다.

- 결과를 확인합니다.

## 10. 데이터프레임 연결

- 데이터프레임 연결은 **pd.concat()** 함수를 사용합니다.
- 중간 결과인 sales_long과 grade_dummy를 연결해 **sales** 데이터프레임을 만듭니다.

- 결과를 확인합니다.

## 11. 불필요한 열 제거 #1

- 년, 월, 일을 추출했으니 **Date** 열은 제거합니다.

- 등급 정보를 가변수와 했으니 **Grade** 열은 제거합니다.

- 월 판매 건수이므로 **Day** 열 값이 의미가 없으니 제거합니다.

- Location 열의 값이 SEOUL 뿐이니 제거합니다.

- 결과를 확인합니다.

## 12. 데이터프레임 조인

- 조인은 **pd.merge()** 함수를 사용합니다.

**1) product 정보 읽어 조인**

- 상품 정보는 **my_product.csv** 파일에 있습니다.
- my_product.csv 파일을 read_csv() 함수로 읽어옵니다.
- 데이터프레임 이름은 **product**로 합니다.
- 'https://raw.githubusercontent.com/Jangrae/csv/master/my_product.csv'

- 데이터를 확인합니다.

- **pd.merge()** 함수를 사용해 ProductID 열을 기준으로 두 데이터를 조인합니다.
- 조인 결과는 **sales** 데이터프레임에 다시 저장합니다.
- 단, 필요한 **ProductID**, **ProductName** 열만 가져와 조인합니다.

- 결과를 확인합니다.

**2) category 정보 읽어 조인**

- **my_category.csv** 파일을 read_csv() 함수로 읽어와 조인합니다.
- 데이터프레임 이름은 **category**로 합니다.
- 'https://raw.githubusercontent.com/Jangrae/csv/master/my_category.csv'

- 읽어온 데이터를 학인합니다.

- pd.merge() 함수를 사용해 조인합니다.
- 조인 결과는 **sales** 데이터프레임에 다시 저장합니다.

- 결과를 확인합니다.

## 13. 불필요한 열 제거 #2

- ProductName 열이 있어 **ProductID**가 필요 없으니 제거합니다.

- 결과를 확인합니다.

## 13. 열 이름 변경 #2

- 추가된 열들이 많습니다.
- 분석의 편의를 위해 추가된 열 이름을 적절히 변경합니다.
- qty, year, month, product, category

- 결과를 확인합니다.

## 14. 결측치 처리 #1

dropna() 메소드를 사용해 NaN 값이 있는 행은 제거합니다.

- 열 정보를 다시 확인합니다.

## 15. 열 순서 변경

- 분석과 열 순서는 관계가 없지만, 분석에 조금이라도 도움이 된다면 열 순서를 변경하는 것이 좋습니다.
- 열 순서를 적절히 변경합니다.

- 결과를 확인합니다.

## 16. 인덱스 초기화

- **reset_index()** 메소드를 사용해 인덱스를 초기하 합니다.
- **drop=True** 옵션을 설정해 기존 인덱스는 버리도록 합니다.

- 결과를 확인합니다.

## 17. 롤링 & 시프트

- 우선 2015, 2016년 월 판매 수량 합을 집계해서 **sales_new** 데이터프레임을 만듭니다.
- groupby()

- 결과를 확인합니다.

- 현재 qty와 하루 전 qty 값을 비교할 것이면 qty 값을 하나씩 아래에 표시하면 됩니다.
- **shift()** 메소드에 이동할 행 수를 지정하면 됩니다.
- shift한 결과를 **prev_qty**열로 추가합니다.

In [0]:
sales_new['prev_qty'] = sales_new['qty'].shift(1)

- 현재 월을 포함해서 최근 3개월 판매 수량 평균을 **lag3_qty_1** 열로 추가합니다.

In [0]:
sales_new['lag3_qty_1'] = sales_new['qty'].rolling(3, min_periods=1).mean()

- 현재 월을 포함하지 않은 직전 3개월 판매 수량 평균을 **lag3_qty_2** 열로 추가합니다.

In [0]:
sales_new['lag3_qty_2'] = sales_new['qty'].rolling(3, min_periods=1).mean().shift(1)

- 결과를 확인합니다.

In [0]:
sales_new

## 18. 결측치 처리 #2

- 집계 과정에서 **lag3_qty_2** 열 맨 앞에 여전히 NaN 값이 있습니다.
- **fillna()** 메소드에 **method='bfill'**를 지정하여 바로 뒤의 값으로 채웁니다.

In [0]:
sales_new.fillna(method='bfill', inplace=True)

- 결과를 확인합니다.

In [0]:
sales_new

## 19. 반올림

- lag3_qty_1, lag3_qty_2 열 값 소수점이 다소 거슬립니다.
- 판매 수량이니 소수점을 없애기 위해 **round()** 메소드로 **반올림** 합니다.

In [0]:
sales_new['lag3_qty_1'] = sales_new['lag3_qty_1'].round(0)
sales_new['lag3_qty_2'] = sales_new['lag3_qty_2'].round(0)

- 결과를 확인합니다.

In [0]:
sales_new

## <center>수고하셨습니다.</center>
<center><img src='https://raw.githubusercontent.com/Jangrae/img/master/end.png' width=200/></center>